[versions]
com-spotify-mobius = "1.5.8"

[libraries]
androidx-appcompat = "androidx.appcompat:appcompat:1.6.0-alpha01"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.3"
androidx-corektx = "androidx.core:core-ktx:1.9.0-alpha01"
androidx-espresso-core = "androidx.test.espresso:espresso-core:3.5.0-alpha04"
androidx-junit = "androidx.test.ext:junit:1.1.4-alpha04"
androidx-lifecycle-common = "androidx.lifecycle:lifecycle-common:2.5.0-alpha03"
junit = "junit:junit:4.13.2"
mobius-android = { module = "com.spotify.mobius:mobius-android", version.ref = "com-spotify-mobius" }
mobius-test = { module = "com.spotify.mobius:mobius-test", version.ref = "com-spotify-mobius" }
truth = "com.google.truth:truth:1.1.3"
